-- Схема базы данных «Партнеры и отгрузки», PostgreSQL, 3-я нормальная форма.
-- Имена в snake_case, названия таблиц в единственном числе.
-- Удаление идет в обратном порядке зависимостей: сначала таблица delivery.

DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS partner;

-- Партнер: реквизиты и контакты. ИНН и почта уникальны.
CREATE TABLE partner (
    partner_id    INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    company_name  VARCHAR(150)  NOT NULL,
    inn           VARCHAR(12)   NOT NULL,
    contact_email VARCHAR(150)  NOT NULL,
    phone         VARCHAR(20),
    rating        DECIMAL(2, 1),
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT partner_pk PRIMARY KEY (partner_id),
    CONSTRAINT partner_inn_uk UNIQUE (inn),
    CONSTRAINT partner_email_uk UNIQUE (contact_email),
    CONSTRAINT partner_inn_ck CHECK (inn ~ '^[0-9]{10}$|^[0-9]{12}$'),
    CONSTRAINT partner_email_ck CHECK (contact_email LIKE '%_@_%.__%'),
    CONSTRAINT partner_rating_ck CHECK (rating >= 0 AND rating <= 5)
);

-- Справочник продукции: название встречается в отгрузках много раз,
-- поэтому вынесено в отдельную таблицу.
CREATE TABLE product (
    product_id   INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(150) NOT NULL,
    CONSTRAINT product_pk PRIMARY KEY (product_id),
    CONSTRAINT product_name_uk UNIQUE (product_name)
);

-- Отгрузка: факт поставки продукции партнеру.
CREATE TABLE delivery (
    delivery_id   INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    partner_id    INTEGER        NOT NULL,
    product_id    INTEGER        NOT NULL,
    delivery_date DATE           NOT NULL,
    quantity      INTEGER        NOT NULL,
    total_amount  DECIMAL(12, 2) NOT NULL,
    CONSTRAINT delivery_pk PRIMARY KEY (delivery_id),
    CONSTRAINT delivery_partner_fk FOREIGN KEY (partner_id)
        REFERENCES partner (partner_id) ON DELETE RESTRICT,
    CONSTRAINT delivery_product_fk FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE RESTRICT,
    CONSTRAINT delivery_quantity_ck CHECK (quantity > 0),
    CONSTRAINT delivery_amount_ck CHECK (total_amount >= 0)
);

CREATE INDEX delivery_partner_idx ON delivery (partner_id);
CREATE INDEX delivery_product_idx ON delivery (product_id);
CREATE INDEX delivery_date_idx ON delivery (delivery_date);
